//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordCounter.Tests.Cases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordCounter.Tests.Cases.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go do that thing that you do so well.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to            
        ///   
        ///.
        /// </summary>
        internal static string Input10 {
            get {
                return ResourceManager.GetString("Input10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quick brown fox jumps over the lazy dog.
        /// </summary>
        internal static string Input2 {
            get {
                return ResourceManager.GetString("Input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.
        /// </summary>
        internal static string Input3 {
            get {
                return ResourceManager.GetString("Input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With hard work, we can achieve greatness. With hard work, we can overcome obstacles. With hard work, we can reach our goals..
        /// </summary>
        internal static string Input4 {
            get {
                return ResourceManager.GetString("Input4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ultricies mauris in metus pulvinar sodales. Suspendisse quis lorem enim. Aenean sapien purus, tristique at vehicula a, luctus at massa. Mauris sagittis sapien quis pharetra volutpat. Maecenas sed elementum lorem, a maximus neque. Vivamus eleifend imperdiet enim, a suscipit diam consequat in. Curabitur sit amet sapien consectetur, pharetra nunc in, gravida dolor. Duis eu aliquam neque, nec accumsan tortor. Morbi eget ligula placerat, rutrum quam  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input5 {
            get {
                return ResourceManager.GetString("Input5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , , Everything that is: a non-whitespace-string-of-characters is a $$$WORD , .. . . .   ..
        /// </summary>
        internal static string Input6 {
            get {
                return ResourceManager.GetString("Input6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the beginning God created the heaven and the earth.
        ///And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.
        ///And God said, Let there be light: and there was light.
        ///And God saw the light, that it was good: and God divided the light from the darkness.
        ///And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.
        ///And God said, Let there be a firmament in the midst of th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input7 {
            get {
                return ResourceManager.GetString("Input7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na początku Bóg stworzył niebo i ziemię.
        ///Ziemia zaś była bezładem i pustkowiem: ciemność była nad powierzchnią bezmiaru wód, a Duch Boży unosił się nad wodami.
        ///Wtedy Bóg rzekł: «Niechaj się stanie światłość!» I stała się światłość.
        ///Bóg widząc, że światłość jest dobra, oddzielił ją od ciemności.
        ///I nazwał Bóg światłość dniem, a ciemność nazwał nocą.
        ///I tak upłynął wieczór i poranek - dzień pierwszy..
        /// </summary>
        internal static string Input8 {
            get {
                return ResourceManager.GetString("Input8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На початку Бог створив Небо та землю.
        ///А земля була пуста та порожня, і темрява була над безоднею, і Дух Божий ширяв над поверхнею води.
        ///І сказав Бог: Хай станеться світло! І сталося світло.
        ///І побачив Бог світло, що добре воно, і Бог відділив світло від темряви.
        ///І Бог назвав світло: День, а темряву назвав: Ніч. І був вечір, і був ранок, день перший..
        /// </summary>
        internal static string Input9 {
            get {
                return ResourceManager.GetString("Input9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2: do
        ///2: that
        ///1: Go
        ///1: so
        ///1: thing
        ///1: well
        ///1: you.
        /// </summary>
        internal static string Output1 {
            get {
                return ResourceManager.GetString("Output1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Output10 {
            get {
                return ResourceManager.GetString("Output10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1: The
        ///1: brown
        ///1: dog
        ///1: fox
        ///1: jumps
        ///1: lazy
        ///1: over
        ///1: quick
        ///1: the.
        /// </summary>
        internal static string Output2 {
            get {
                return ResourceManager.GetString("Output2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5: buffalo
        ///3: Buffalo.
        /// </summary>
        internal static string Output3 {
            get {
                return ResourceManager.GetString("Output3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3: With
        ///3: can
        ///3: hard
        ///3: we
        ///3: work,
        ///1: achieve
        ///1: goals.
        ///1: greatness.
        ///1: obstacles.
        ///1: our
        ///1: overcome
        ///1: reach.
        /// </summary>
        internal static string Output4 {
            get {
                return ResourceManager.GetString("Output4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8: vitae
        ///5: id
        ///5: in
        ///5: quis
        ///4: a
        ///4: eget
        ///4: gravida
        ///4: lacinia
        ///4: nec
        ///4: tellus
        ///3: Curabitur
        ///3: Morbi
        ///3: Sed
        ///3: at
        ///3: et
        ///3: felis
        ///3: imperdiet
        ///3: ipsum
        ///3: metus
        ///3: sapien
        ///3: sodales
        ///3: volutpat.
        ///2: Aliquam
        ///2: Donec
        ///2: Duis
        ///2: Maecenas
        ///2: Mauris
        ///2: Praesent
        ///2: Proin
        ///2: Ut
        ///2: a,
        ///2: aliquam
        ///2: commodo
        ///2: diam
        ///2: dignissim
        ///2: dui
        ///2: efficitur.
        ///2: eleifend
        ///2: erat
        ///2: eros
        ///2: est
        ///2: est.
        ///2: feugiat
        ///2: interdum
        ///2: massa
        ///2: massa.
        ///2: mattis
        ///2: maximus
        ///2: mi
        ///2: neque,
        ///2: non
        ///2: nunc
        ///2: per
        ///2: pharetra
        ///2: risus
        ///2: s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Output5 {
            get {
                return ResourceManager.GetString("Output5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4: .
        ///3: ,
        ///2: a
        ///1: $$$WORD
        ///1: ..
        ///1: Everything
        ///1: is
        ///1: is:
        ///1: non-whitespace-string-of-characters
        ///1: that.
        /// </summary>
        internal static string Output6 {
            get {
                return ResourceManager.GetString("Output6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 108: the
        ///63: and
        ///33: And
        ///32: God
        ///20: of
        ///17: was
        ///15: it
        ///14: that
        ///13: in
        ///12: every
        ///11: after
        ///11: to
        ///10: over
        ///10: upon
        ///9: his
        ///9: said,
        ///8: Let
        ///8: earth
        ///8: waters
        ///8: were
        ///7: be
        ///7: firmament
        ///7: light
        ///7: saw
        ///6: day.
        ///6: earth,
        ///6: evening
        ///6: for
        ///6: fowl
        ///6: good.
        ///6: he
        ///6: kind,
        ///6: let
        ///6: morning
        ///6: so.
        ///5: called
        ///5: created
        ///5: forth
        ///5: from
        ///5: heaven
        ///5: there
        ///5: thing
        ///5: which
        ///5: yielding
        ///4: earth.
        ///4: have
        ///4: herb
        ///4: is
        ///4: kind:
        ///4: made
        ///4: them
        ///3: air,
        ///3: beast
        ///3: bring
        ///3: creature
        ///3: creepeth
        ///3: divide
        ///3: face
        ///3: fru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Output7 {
            get {
                return ResourceManager.GetString("Output7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4: Bóg
        ///3: I
        ///3: i
        ///3: się
        ///2: a
        ///2: była
        ///2: ciemność
        ///2: nad
        ///2: nazwał
        ///2: światłość
        ///1: -
        ///1: Boży
        ///1: Duch
        ///1: Na
        ///1: Wtedy
        ///1: Ziemia
        ///1: bezmiaru
        ///1: bezładem
        ///1: ciemności.
        ///1: dniem,
        ///1: dobra,
        ///1: dzień
        ///1: jest
        ///1: ją
        ///1: niebo
        ///1: nocą.
        ///1: od
        ///1: oddzielił
        ///1: pierwszy.
        ///1: początku
        ///1: poranek
        ///1: powierzchnią
        ///1: pustkowiem:
        ///1: rzekł:
        ///1: stanie
        ///1: stała
        ///1: stworzył
        ///1: tak
        ///1: unosił
        ///1: upłynął
        ///1: widząc,
        ///1: wieczór
        ///1: wodami.
        ///1: wód,
        ///1: zaś
        ///1: ziemię.
        ///1: «Niechaj
        ///1: światłość!»
        ///1: światłość.
        ///1: że.
        /// </summary>
        internal static string Output8 {
            get {
                return ResourceManager.GetString("Output8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5: І
        ///4: Бог
        ///4: і
        ///2: був
        ///2: була
        ///2: над
        ///2: та
        ///1: А
        ///1: Бог:
        ///1: Божий
        ///1: День,
        ///1: Дух
        ///1: На
        ///1: Небо
        ///1: Ніч.
        ///1: Хай
        ///1: а
        ///1: безоднею,
        ///1: вечір,
        ///1: води.
        ///1: воно,
        ///1: від
        ///1: відділив
        ///1: день
        ///1: добре
        ///1: землю.
        ///1: земля
        ///1: назвав
        ///1: назвав:
        ///1: перший.
        ///1: побачив
        ///1: поверхнею
        ///1: порожня,
        ///1: початку
        ///1: пуста
        ///1: ранок,
        ///1: світло
        ///1: світло!
        ///1: світло,
        ///1: світло.
        ///1: світло:
        ///1: сказав
        ///1: сталося
        ///1: станеться
        ///1: створив
        ///1: темрява
        ///1: темряви.
        ///1: темряву
        ///1: ширяв
        ///1: що.
        /// </summary>
        internal static string Output9 {
            get {
                return ResourceManager.GetString("Output9", resourceCulture);
            }
        }
    }
}
